version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
    groups:
      pytorch-ecosystem:
        patterns:
          - "torch*"
          - "torchvision"
          - "torchaudio"
      ml-dependencies:
        patterns:
          - "numpy"
          - "scipy"
          - "matplotlib"
          - "scikit-learn"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"
          - "isort"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"