global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PWMK application metrics
  - job_name: 'pwmk-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    
  # System metrics via node_exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
      
  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # GPU metrics (if available)
  - job_name: 'gpu-metrics'
    static_configs:
      - targets: ['host.docker.internal:9400']
    scrape_interval: 5s